package service.nextoneday.com.aidlservice.HMD;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import service.nextoneday.com.aidlservice.HMD.LogTable;
import service.nextoneday.com.aidlservice.HMD.VarTable;

import service.nextoneday.com.aidlservice.HMD.LogTableDao;
import service.nextoneday.com.aidlservice.HMD.VarTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logTableDaoConfig;
    private final DaoConfig varTableDaoConfig;

    private final LogTableDao logTableDao;
    private final VarTableDao varTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logTableDaoConfig = daoConfigMap.get(LogTableDao.class).clone();
        logTableDaoConfig.initIdentityScope(type);

        varTableDaoConfig = daoConfigMap.get(VarTableDao.class).clone();
        varTableDaoConfig.initIdentityScope(type);

        logTableDao = new LogTableDao(logTableDaoConfig, this);
        varTableDao = new VarTableDao(varTableDaoConfig, this);

        registerDao(LogTable.class, logTableDao);
        registerDao(VarTable.class, varTableDao);
    }
    
    public void clear() {
        logTableDaoConfig.clearIdentityScope();
        varTableDaoConfig.clearIdentityScope();
    }

    public LogTableDao getLogTableDao() {
        return logTableDao;
    }

    public VarTableDao getVarTableDao() {
        return varTableDao;
    }

}
